///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Autothon
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutothonRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("7119c654-9643-4e03-a7fb-598f04e48455")]
    public partial class AutothonRepository : RepoGenBaseFolder
    {
        static AutothonRepository instance = new AutothonRepository();

        /// <summary>
        /// Gets the singleton class instance representing the AutothonRepository element repository.
        /// </summary>
        [RepositoryFolder("7119c654-9643-4e03-a7fb-598f04e48455")]
        public static AutothonRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutothonRepository() 
            : base("AutothonRepository", "/", null, 0, false, "7119c654-9643-4e03-a7fb-598f04e48455", ".\\RepositoryImages\\AutothonRepository7119c654.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7119c654-9643-4e03-a7fb-598f04e48455")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class AutothonRepositoryFolders
    {
    }
#pragma warning restore 0436
}