///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DataLayer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DataLayerRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("244435e1-fbaf-47fa-82d4-9786d4f9c2fe")]
    public partial class DataLayerRepository : RepoGenBaseFolder
    {
        static DataLayerRepository instance = new DataLayerRepository();

        /// <summary>
        /// Gets the singleton class instance representing the DataLayerRepository element repository.
        /// </summary>
        [RepositoryFolder("244435e1-fbaf-47fa-82d4-9786d4f9c2fe")]
        public static DataLayerRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DataLayerRepository() 
            : base("DataLayerRepository", "/", null, 0, false, "244435e1-fbaf-47fa-82d4-9786d4f9c2fe", ".\\RepositoryImages\\DataLayerRepository244435e1.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("244435e1-fbaf-47fa-82d4-9786d4f9c2fe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class DataLayerRepositoryFolders
    {
    }
#pragma warning restore 0436
}